export interface AgentConfig {
  agent_key: string;
  agent_name: string;
  sector_name: string;
  colour: string;
  tickers: string[];
  companies: string[];
  hasSweep: boolean;
}

export const AGENTS: AgentConfig[] = [
  {
    agent_key: 'apex',
    agent_name: 'APEX',
    sector_name: 'AU Enterprise Software',
    colour: 'green',
    hasSweep: true,
    tickers: ['WTC', 'XRO', 'PME', 'REA', 'SEK'],
    companies: ['WiseTech Global', 'Xero', 'Pro Medicus', 'REA Group', 'Seek'],
  },
  {
    agent_key: 'crypto',
    agent_name: 'CRYPTO',
    sector_name: 'Cryptocurrency',
    colour: 'purple',
    hasSweep: false,
    tickers: [],
    companies: [],
  },
  {
    agent_key: 'dragon',
    agent_name: 'DRAGON',
    sector_name: 'China Semis',
    colour: 'sky',
    hasSweep: true,
    tickers: ['688981.SS', '688256.SS', '688041.SS', '603501.SS', '688008.SS'],
    companies: ['SMIC (A-shares)', 'Cambricon', 'Hygon', 'Will Semiconductor', 'Montage Technology'],
  },
  {
    agent_key: 'ferro',
    agent_name: 'FERRO',
    sector_name: 'MLCCs',
    colour: 'red',
    hasSweep: true,
    tickers: ['6981.T', '6762.T', '2327.TW', '009150.KS'],
    companies: ['Murata Manufacturing', 'TDK Corp', 'Yageo Corp', 'Samsung Electro-Mechanics'],
  },
  {
    agent_key: 'forge',
    agent_name: 'FORGE',
    sector_name: 'Semi Equipment ex-Japan',
    colour: 'teal',
    hasSweep: true,
    tickers: ['AMAT', '3711.TW', 'ASML', 'KLAC', 'LRCX', '002371.SZ', '688012.SS', '688200.SS', '688082.SS', '688072.SS'],
    companies: ['Applied Materials', 'ASE Technology', 'ASML', 'KLA', 'Lam Research', 'NAURA Technology', 'AMEC (Advanced Micro-Fabrication)', 'Beijing Huafeng Test', 'ACM Research Shanghai', 'Piotech'],
  },
  {
    agent_key: 'forge_jp',
    agent_name: 'FORGE_JP',
    sector_name: 'Semi Equipment Japan',
    colour: 'teal',
    hasSweep: true,
    tickers: ['6857.T', '6146.T', '6361.T', '7741.T', '6525.T', '6920.T', '6323.T', '7735.T', '8035.T', '7729.T'],
    companies: ['Advantest', 'Disco', 'TOWA', 'HOYA', 'Kokusai Electric', 'Lasertec', 'Rorze', 'Screen Holdings', 'Tokyo Electron', 'Tokyo Seimitsu'],
  },
  {
    agent_key: 'helix',
    agent_name: 'HELIX',
    sector_name: 'Memory Semis',
    colour: 'amber',
    hasSweep: true,
    tickers: ['285A.T', 'MU', '005930.KS', 'SNDK', 'STX', '000660.KS', '2408.TW'],
    companies: ['Kioxia', 'Micron', 'Samsung Electronics', 'Western Digital', 'Seagate', 'SK Hynix', 'Nanya Technology'],
  },
  {
    agent_key: 'indra',
    agent_name: 'INDRA',
    sector_name: 'India IT Services',
    colour: 'purple',
    hasSweep: true,
    tickers: ['INFY.NS', 'TCS.NS', 'TECHM.NS', 'WIPRO.NS'],
    companies: ['Infosys', 'TCS', 'Tech Mahindra', 'Wipro'],
  },
  {
    agent_key: 'keynes',
    agent_name: 'KEYNES',
    sector_name: 'Global Macro',
    colour: 'slate',
    hasSweep: false,
    tickers: [],
    companies: [],
  },
  {
    agent_key: 'layer',
    agent_name: 'LAYER',
    sector_name: 'PCB Supply-chain',
    colour: 'gold',
    hasSweep: true,
    tickers: ['007660.KS', '2368.TW', '3037.TW', '1303.TW', '002916.SZ', '002463.SZ', '300476.SZ', '3189.TW', '600183.SS', '8046.TW'],
    companies: ['Isu Petasys', 'Gold Circuit Electronics', 'Unimicron Technology', 'Nanya Plastics', 'Shennan Circuits', 'WUS Printed Circuit', 'Victory Giant Technology', 'Kinsus Interconnect', 'Shengyi Technology', 'Nan Ya Printed Circuit'],
  },
  {
    agent_key: 'mario',
    agent_name: 'MARIO',
    sector_name: 'Japan Gaming',
    colour: 'pink',
    hasSweep: true,
    tickers: ['6758.T', '7974.T', '9766.T', '9697.T', '7832.T', '6460.T'],
    companies: ['Sony Group', 'Nintendo', 'Konami', 'Capcom', 'Bandai Namco', 'Sega Sammy'],
  },
  {
    agent_key: 'masa',
    agent_name: 'MASA',
    sector_name: 'Japan Internet',
    colour: 'cyan',
    hasSweep: true,
    tickers: ['9984.T', '4755.T', '4689.T', '4385.T', '3092.T'],
    companies: ['SoftBank Group', 'Rakuten Group', 'LY Corp', 'Mercari', 'Zozo'],
  },
  {
    agent_key: 'miner',
    agent_name: 'MINER',
    sector_name: 'Mining',
    colour: 'stone',
    hasSweep: false,
    tickers: [],
    companies: [],
  },
  {
    agent_key: 'nova',
    agent_name: 'NOVA',
    sector_name: 'AI Semis',
    colour: 'amber',
    hasSweep: true,
    tickers: ['2330.TW', 'NVDA', 'AVGO', 'AMD', '2454.TW', 'MRVL'],
    companies: ['TSMC', 'Nvidia', 'Broadcom', 'AMD', 'MediaTek', 'Marvell Technology'],
  },
  {
    agent_key: 'optim',
    agent_name: 'OPTIM',
    sector_name: 'Grid Power & Transformers',
    colour: 'orange',
    hasSweep: true,
    tickers: ['6501.T', '267260.KS', '002028.SZ'],
    companies: ['Hitachi', 'HD Hyundai Electric', 'Sieyuan Electric'],
  },
  {
    agent_key: 'orient',
    agent_name: 'ORIENT',
    sector_name: 'China Digital Consumption',
    colour: 'blue',
    hasSweep: true,
    tickers: ['9988.HK', 'BIDU', 'NTES', '700.HK', 'PDD'],
    companies: ['Alibaba', 'Baidu', 'NetEase', 'Tencent', 'PDD Holdings'],
  },
  {
    agent_key: 'orient_mid',
    agent_name: 'ORIENT_MID',
    sector_name: 'China Mid-Caps',
    colour: 'blue',
    hasSweep: true,
    tickers: ['1024.HK', 'FUTU', 'BILI', 'TCOM', 'TME'],
    companies: ['Kuaishou', 'Futu Holdings', 'Bilibili', 'Trip.com', 'Tencent Music'],
  },
  {
    agent_key: 'photon',
    agent_name: 'PHOTON',
    sector_name: 'Networking & Optics',
    colour: 'red',
    hasSweep: true,
    tickers: ['2345.TW', 'CLS', 'COHR', 'FN', 'LITE', '300394.SZ', '300502.SZ'],
    companies: ['Accton Technology', 'Celestica', 'Coherent', 'Fabrinet', 'Lumentum', 'Suzhou TFC Optical', 'Zhongji Innolight'],
  },
  {
    agent_key: 'pilbara',
    agent_name: 'PILBARA',
    sector_name: 'Iron Ore',
    colour: 'stone',
    hasSweep: true,
    tickers: ['BHP', 'RIO', 'FMG'],
    companies: ['BHP', 'Rio Tinto', 'Fortescue Metals'],
  },
  {
    agent_key: 'pixel',
    agent_name: 'PIXEL',
    sector_name: 'Gaming',
    colour: 'blue',
    hasSweep: true,
    tickers: ['EA', 'TTWO'],
    companies: ['Electronic Arts', 'Take-Two Interactive'],
  },
  {
    agent_key: 'rack',
    agent_name: 'RACK',
    sector_name: 'Server ODMs',
    colour: 'teal',
    hasSweep: true,
    tickers: ['2317.TW', '2382.TW', '3231.TW'],
    companies: ['Hon Hai / Foxconn', 'Quanta Computer', 'Wistron'],
  },
  {
    agent_key: 'rocket',
    agent_name: 'ROCKET',
    sector_name: 'Defence Hardware',
    colour: 'slate',
    hasSweep: true,
    tickers: ['012450.KS', '047810.KS', '064350.KS', '079550.KS', '272210.KS'],
    companies: ['Hanwha Aerospace', 'Korea Aerospace Industries', 'Hyundai Rotem', 'LIG Nex1', 'Hanwha Systems'],
  },
  {
    agent_key: 'shrink',
    agent_name: 'SHRINK',
    sector_name: 'Investment Philosophy',
    colour: 'slate',
    hasSweep: false,
    tickers: [],
    companies: [],
  },
  {
    agent_key: 'surge',
    agent_name: 'SURGE',
    sector_name: 'EV Supply-chain',
    colour: 'pink',
    hasSweep: true,
    tickers: ['TSLA', '1211.HK', '300750.SZ', '1810.HK', '373220.KS'],
    companies: ['Tesla', 'BYD', 'CATL', 'Xiaomi', 'LG Energy Solution'],
  },
  {
    agent_key: 'synth',
    agent_name: 'SYNTH',
    sector_name: 'China AI Apps',
    colour: 'lime',
    hasSweep: true,
    tickers: ['0100.HK', '2513.HK'],
    companies: ['MiniMax Group', 'Zhipu AI'],
  },
  {
    agent_key: 'terra',
    agent_name: 'TERRA',
    sector_name: 'Japan Materials',
    colour: 'green',
    hasSweep: true,
    tickers: ['4004.T', '3110.T', '3436.T', '5016.T', '4062.T'],
    companies: ['Resonac Holdings', 'Nitto Boseki', 'SUMCO Corp', 'JX Advanced Metals', 'Ibiden'],
  },
  {
    agent_key: 'tide',
    agent_name: 'TIDE',
    sector_name: 'ASEAN E-commerce',
    colour: 'purple',
    hasSweep: true,
    tickers: ['GRAB', 'SE'],
    companies: ['Grab Holdings', 'Sea Limited'],
  },
  {
    agent_key: 'volt',
    agent_name: 'VOLT',
    sector_name: 'DC Power & Cooling',
    colour: 'gold',
    hasSweep: true,
    tickers: ['VRT', '2308.TW', '2301.TW', '002851.SZ'],
    companies: ['Vertiv', 'Delta Electronics', 'Lite-On Technology', 'Shenzhen Megmeet'],
  },
];

export const getAgent = (key: string) => AGENTS.find(a => a.agent_key === key.toLowerCase());
